# Generated by Django 4.2.4 on 2023-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_image_alter_orderitem_item_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
